### PR TITLE
Removed dependency on bash extglob shopt in _module_dir function.

### PR DESCRIPTION
**Pull request by pneerincx**

### CODE REVIEW

**Comment by rtmclay** [comment]
Thanks for the patch!  This patch is installed as 6.5.9.  @boegel please test this when you can. Thanks!

**Comment by boegel** [comment]
@rtmclay tag for 6.5.9 is missing?

**Comment by boegel** [comment]
OK, fix is trivial enough to apply by hand in existing installation.

Tab completion on `ml use $TEST<tab>` with `$TESTDIR` defined as an existing dir now works like a charm, thanks @pneerincx!

**Comment by rtmclay** [comment]
I have now pushed 6.5.9.  Sorry about the delay.

**Pull request merged**
