### PR TITLE
Add hook

### PR DESCRIPTION
**Pull request by wpoely86**
This adds a hook that allows you to manipulate what is shown in `ml av`. You can filter out certain module as you wish. Keep in mind that this is costly: it's called for every module in avail.

Thoughts @rtmclay? Good idea, bad idea, blow-your-foot-off idea?

### CODE REVIEW

**Comment by rtmclay** [comment]
I guess I don't understand why you'd want to do that.  Why do this when you can use hidden modules?

**Comment by wpoely86** [comment]
Flexibility mostly. With this, hidden can be done dynamic. You can hide modules from users in `ml av` and yet let them work fine when loading (no dot required). You can show modules depending on the user and the location, ...

**Comment by rtmclay** [comment]
I am willing to accept a programming way to support hidden modules.  But it has to part of MRC:isVisible(). That way it works the same as marking modules as hidden in the ~/.modulerc file or the system MODULERC.  Also --show_hidden will be supported.  I want this to work for both avail and spider.

Unfortunately,  It's MRC:isVisible(fullName) and not MRC:isVisible(Table) where Table is {sn, fn, fullName).  It will take a little  work to change the interface to MRC:isVisible().   Please let me know if you interested in making change.  Otherwise I'll get to it later.

**Comment by wpoely86** [comment]
Alternative implementation in #270

**Pull request closed without merging**
