### PR TITLE
add bash completion script for module command

### PR DESCRIPTION
**Pull request by hjelmn**
This commit adds a bash completion script supporting both the legacy
module and the new lmod module system. If bash completion is installed
his script can be installed system-wide in /etc/bash_completion.d or
in a user's  ~/.bash_completion.d directory.

Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>

### CODE REVIEW

**Comment by hjelmn** [comment]
The script has legacy module support for environments where some systems have legacy modules and some systems have lmod.

**Comment by hjelmn** [comment]
Added a README to the completion directory. I plan to add completion for zsh in the future if no one beats me to it.

**Comment by rtmclay** [comment]
This looks very useful.  Thanks for submitting it.  

Is there any reason why this can't replace init/lmod_bash_completion?

**Comment by hjelmn** [comment]
Hah, actually didn't see the other one. This is a script I have had around for awhile I had to update now that TOSS uses lmod. There are a couple things the existing script does that mine doesn't. I could update it to include those features and update the PR if you like.

**Comment by rtmclay** [comment]
Yes, please merge the two.  Thanks,

**Pull request closed without merging**
