### PR TITLE
add versioning for lua

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

---

All tests are passing, please also try running them locally to make sure that they are working correctly.

There is more work to be done though.
List of thing still to be done:
- Remove all invocations of lua during compile time in `configure.ac`
   - Allow `configure.ac` to skip checking modules, modules are not needed at install time.
   - Allow `SYS_LUA_PATH` and `SYS_LUA_CPATH` to be given as parameters.
- Remove all invokations of lua in Makefile.in
   - Debatable, it does not seem to be used for getting config information, but more for doing scripting work. In which case it doesn't matter what lua version is used.
- Fix tests to use versioned `luac@LUA_SUFFIX_VERSION`, they seem to still be using `luac` but should have no effect for anybody, as `@LUA_SUFFIX_VERSION@` is empty anyway.

### CODE REVIEW

**Comment by rtmclay** [comment]
I have looked over the PR and there are some issues. The tests for luaposix etc. must stay in by default. Most sites are going to use the same version of lua and the configure tests make sure that they have luaposix installed.  That has to be done at configure time.  If you want a delay then that has to be a new configure option which says I know what I'm doing and luaposix etc will be there on the install machine.

**Comment by epsilon-0** [comment]
@rtmclay 
The tests for all lua modules are still there.
Can you clarify what I've removed?

**Comment by rtmclay** [comment]
I have merged in this PR using a patch file.  I have done several things to this PR:

1.  I have required that both --with-lua and --with-luac must both be specified if one is.
2.  I have added --with-luaSuffix=. This config option cannot be used with --with-lua or --with-luac
3.  I already had the **proj_mgmt** directory so I moved the helper files into that directory
4.  I changed finding the lua include directory logic back to what is was before.  I have merged in what I think you were doing.

The 4th change is something that you might want to test.  It is important that the lua include directory be found when lua is installed in an optional directory.

**Comment by epsilon-0** [comment]
> I changed finding the lua include directory logic back to what is was before. I have merged in what I think you were doing.

OMG!!! I'm so sorry, I forgot to add it back in, when I was testing!!!
Thanks so much for fixing that! :heart: 

And thanks a lot for the fixes!
This is really helpful. I will test and report back.

**Comment by epsilon-0** [comment]
Amazing, thanks for this.
I have tested the compilation locally and also ran the test suite, everything is passing!
I really appreciate the change :smiley_cat:

**Pull request closed without merging**
