### PR TITLE
LMOD_SYSTEM_DEFAULT_MODULES should be conditional on not being predefined elsewhere

### PR DESCRIPTION
**Pull request by fgeorgatos**
is there a reason for not having it that way already?!

### CODE REVIEW

**Comment by fgeorgatos** [comment]
p.s. I have something similar in production but not exactly this. Please test just in case...

**Comment by rtmclay** [comment]
My view is that sites should change
     export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv"
to
     export LMOD_SYSTEM_DEFAULT_MODULES="WHAT:EVER:THE:SITE:WANTS"

That is sites should control what list of modules a site here.   I'm perfectly willing to change the words around to communicate that.

**Comment by fgeorgatos** [comment]
Hi Robert,

I've entered the business of packaging Lmod for multiple HPC sites.

So we need to generalised the configuration, yet not at the expense of
automated upgrades.
I will provide some more details via another channel, asap.

F.



On 8 April 2016 at 19:55, Robert McLay <notifications@github.com> wrote:

> My view is that sites should change
> export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv"
> to
> export LMOD_SYSTEM_DEFAULT_MODULES="WHAT:EVER:THE:SITE:WANTS"
>
> That is sites should control what list of modules a site here. I'm
> perfectly willing to change the words around to communicate that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TACC/Lmod/pull/108#issuecomment-207555975>
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by fgeorgatos** [comment]
Hi @rtmclay :
the proposed PR provides the **feature** of being able to independently/externally manage the value of `LMOD_SYSTEM_DEFAULT_MODULES` regardless if the files `z00_StdEnv.*sh` belong to an upstream RPM.

This is important, because they are truly essentially for correct functioning of Lmod, esp. the `refresh` step,
meanwhile, we'd occasionally need to upgrade the version of the Lmod rpms.

fyi. recent Bright packaging has been doing something quite similar, also, for the same reason.
So, could we consider either this PR or, provide the requested feature via some other means?!

**Comment by rtmclay** [comment]
I guess my problem with this patch has been that the documentation here is just supposed to be an example of how to startup Lmod so that a site provides a default set of modules that a user can override with a default collection.  It is NOT meant to be "do it this way or else".  

I have added comments at the bottom of the page to make this point clearer.  Please look over this update to the documentation and see if it clarifies the situation.  If you have suggestions on how to make this clearer, I'll be happy to look at them.

**Comment by fgeorgatos** [comment]
yes, this is much improved, thanks!

a typo : s/are source/are sourced/g

Basically, people to understand that that script is essentially for certain Lmod functionality (save/restore),
as well as having system-wide preloaded modulefiles. IMHO, Lmod is incomplete without them (because documentation lures you towards all those extra features!)

**Pull request merged**
