### PR TITLE
add Travis config for Lmod test suite

### PR DESCRIPTION
**Pull request by boegel**
This is not ready yet, currently 5 tests are failing on Travis (cfr. https://travis-ci.org/boegel/Lmod/builds/136810652). Also, I may squash all commits here, it's a bit messy now.

```
diff     /home/travis/build/boegel/Lmod/rt/delcatty/t1/2016_06_10_21_06_32-Linux-x86_64-delcatty
diff     /home/travis/build/boegel/Lmod/rt/end2end/t1/2016_06_10_21_06_32-Linux-x86_64-end2end
diff     /home/travis/build/boegel/Lmod/rt/errHandler/t1/2016_06_10_21_06_32-Linux-x86_64-errHandler
diff     /home/travis/build/boegel/Lmod/rt/hook/t1/2016_06_10_21_06_32-Linux-x86_64-hook
diff     /home/travis/build/boegel/Lmod/rt/modulerc/t1/2016_06_10_21_06_32-Linux-x86_64-modulerc
```

My analysis:

* `delcatty`, `errHandler` and `modulerc` fails because of line wrapping; I tried to fix this by defining `$LMOD_TERM_WIDTH` and `$COLUMNS` to `80`, but it doesn't help

* `hook`: fails because `uuidgen` is missing; it seems like I would need to install the `uuid-runtime` package should be installed, but it is not whitelisted yet on Travis (see list @ https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)

* `end2end` fails with `ProjectDIR/rt/common_funcs.sh: line 64: OutputDIR/lmod/lmod/libexec/lmod: No such file or directory`; no idea what may be the cause of this...

More detailed diffs for `err.txt` below (diff for `out.txt` is empty for each of these).

* `delcatty` (empty diff for `out.txt`):
```
>>>> rt/delcatty//err.txt
--- rt/delcatty//err.txt	2016-06-10 21:05:59.206541387 +0000
+++ rt/delcatty//t1/2016_06_10_21_06_32-Linux-x86_64-delcatty/err.txt	2016-06-10 21:07:36.785365249 +0000
@@ -2,7 +2,7 @@
 step 1
 lua ProjectDIR/src/lmod.in.lua bash --version
 ===========================
-Modules based on Lua: Version 6.0.26  2016-01-29 11:03
+Modules based on Lua: Version 6.4.1  2016-06-04 08:48
     by Robert McLay mclay@tacc.utexas.edu
 ===========================
 step 2
@@ -23,8 +23,8 @@
 lua ProjectDIR/src/lmod.in.lua bash load Error
 ===========================
 Lmod has detected the following error: Unable to load module: Error
-     ProjectDIR/rt/delcatty/mf/Core/Error/1.0 : Non-zero status
-returned
+     ProjectDIR/rt/delcatty/mf/Core/Error/1.0 : Non-zero
+status returned
 While processing the following module(s):
     Module fullname  Module Filename
     Error/1.0        ProjectDIR/rt/delcatty/mf/Core/Error/1.0
```

* `end2end`
```
--- rt/end2end//err.txt	2016-06-10 21:05:59.210541338 +0000
+++ rt/end2end//t1/2016_06_10_21_06_32-Linux-x86_64-end2end/err.txt	2016-06-10 21:06:34.046121377 +0000
@@ -2,21 +2,20 @@
 step 1
 lua ProjectDIR/src/lmod.in.lua bash --version
 ===========================
-Modules based on Lua: Version 6.0.19  2015-11-18 08:32
+Modules based on Lua: Version 6.4.1  2016-06-04 08:48
     by Robert McLay mclay@tacc.utexas.edu
 ===========================
 step 2
  OutputDIR/lmod/lmod/libexec/lmod --version
 ===========================
-Modules based on Lua: Version 6.0.19 (6.0.19-3-gff50a53) 2015-11-18 08:32
-    by Robert McLay mclay@tacc.utexas.edu
+ProjectDIR/rt/common_funcs.sh: line 64: OutputDIR/lmod/lmod/libexec/lmod: No such file or directory
 ===========================
 step 3
  OutputDIR/lmod/lmod/libexec/lmod load admin
 ===========================
+ProjectDIR/rt/common_funcs.sh: line 64: OutputDIR/lmod/lmod/libexec/lmod: No such file or directory
 ===========================
 step 4
  OutputDIR/lmod/lmod/libexec/lmod list
 ===========================
-Currently Loaded Modules:
-  1) admin/admin-1.0
+ProjectDIR/rt/common_funcs.sh: line 64: OutputDIR/lmod/lmod/libexec/lmod: No such file or directory
```

* `errHandler`
```
--- rt/errHandler//err.txt	2016-06-10 21:05:59.210541338 +0000
+++ rt/errHandler//t1/2016_06_10_21_06_32-Linux-x86_64-errHandler/err.txt	2016-06-10 21:07:17.777594298 +0000
@@ -2,15 +2,15 @@
 step 1
 lua ProjectDIR/src/lmod.in.lua bash --version
 ===========================
-Modules based on Lua: Version 6.0.26  2016-01-29 11:03
+Modules based on Lua: Version 6.4.1  2016-06-04 08:48
     by Robert McLay mclay@tacc.utexas.edu
 ===========================
 step 2
 lua ProjectDIR/src/lmod.in.lua bash load bad_syntax
 ===========================
 Lmod has detected the following error: Unable to load module: bad_syntax
-     ProjectDIR/rt/errHandler/mf/bad_syntax/1.0.lua : [string
-"setenv("BAD_SYNTAX","1.0")..."]:2: unexpected symbol near '#'
+     ProjectDIR/rt/errHandler/mf/bad_syntax/1.0.lua :
+[string "setenv("BAD_SYNTAX","1.0")..."]:2: unexpected symbol near '#'
 While processing the following module(s):
     Module fullname  Module Filename
     bad_syntax/1.0   ProjectDIR/rt/errHandler/mf/bad_syntax/1.0.lua
```

* `hook`
```
--- rt/hook//err.txt	2016-06-10 21:05:59.214541290 +0000
+++ rt/hook//t1/2016_06_10_21_06_32-Linux-x86_64-hook/err.txt	2016-06-10 21:06:43.022013182 +0000
@@ -2,7 +2,7 @@
 step 1
 lua ProjectDIR/src/lmod.in.lua bash --version
 ===========================
-Modules based on Lua: Version 5.0.1 (5.0.1-48-g540fa7d) 2013-06-18 14:14
+Modules based on Lua: Version 6.4.1  2016-06-04 08:48
     by Robert McLay mclay@tacc.utexas.edu
 ===========================
 step 2
@@ -12,3 +12,5 @@
 step 3
 lua ProjectDIR/src/lmod.in.lua bash load admin intel
 ===========================
+sh: 1: uuidgen: not found
+sh: 1: uuidgen: not found
```

* `modulerc`
```
--- rt/modulerc//err.txt	2016-06-10 21:05:59.222541194 +0000
+++ rt/modulerc//t1/2016_06_10_21_06_32-Linux-x86_64-modulerc/err.txt	2016-06-10 21:06:58.417827616 +0000
@@ -2,7 +2,7 @@
 step 1
 lua ProjectDIR/src/lmod.in.lua bash --version
 ===========================
-Modules based on Lua: Version 6.0.19  2015-11-18 08:32
+Modules based on Lua: Version 6.4.1  2016-06-04 08:48
     by Robert McLay mclay@tacc.utexas.edu
 ===========================
 step 2
@@ -154,4 +154,5 @@
 ===========================
 The default cluster module cannot be determined. Please set $VSC_DEFAULT_CLUSTER_MODULE.
 Lmod has detected the following error: Unable to parse:
-ProjectDIR/rt/modulerc/mf2/Core/cluster/.modulerc  Aborting!
+ProjectDIR/rt/modulerc/mf2/Core/cluster/.modulerc
+Aborting!
```

### CODE REVIEW

**Comment by boegel** [comment]
Thanks to @kikito btw, this is heavily based on his talk at FOSDEM on how to test Lua projects on Travis (cfr. https://fosdem.org/2016/schedule/event/continuous_integration_with_lua/, https://kikito.github.io/ci-with-lua).

**Comment by boegel** [comment]
Providing `uuidgen` would require that `uuid-runtime` is supported on Travis, which requires a request like https://github.com/travis-ci/apt-package-whitelist/issues/2772

**Comment by boegel** [comment]
This should be good to go now.

One last trick I had to pull is to fix `$LMOD_TERM_WIDTH` hard in the tests, mostly to `80` but something to a very wide setting to avoid the influence of the lengh of the path to the tests themselves.
Thanks for the help with this @rtmclay!

Travis gives this a green light now, cfr. https://travis-ci.org/boegel/Lmod/builds/138767150 \o/

**Comment by kikito** [comment]
> Thanks to @kikito btw, this is heavily based on his talk at FOSDEM on how to test Lua projects on Travis 

You are welcome, glad to help :)!

**Pull request merged**
