### PR TITLE
Tcl scripts should use tclsh found by configure

### PR DESCRIPTION
**Pull request by hartzell**
The configure script searches for tclsh (and fails if it can't be
found).

This change touches up the makefile and the src/*tcl scripts so that
their `#!` lines use the tclsh that was found at build time rather than
trusting what's found in the environment at run time.

This change is useful for tools like
[spack](https://github.com/llnl/spack), which very carefully manage and
provide prerequisites at build time so that users do not need to be
aware of them at run time.

### CODE REVIEW

**Comment by hartzell** [comment]
The travis build failures seem large.  Are they the result my change or are they an unrelated problem?

**Comment by rtmclay** [comment]
Of course they are.

**Comment by rtmclay** [comment]
There are problems with this solution independent of your changes w.r.t. where to find tclsh.  The reason why Lmod uses:

   /usr/bin/env tclsh

instead of hardcoding the path to tclsh is that Lmod could be configured with an older version of tclsh.  Then a user may have there own installation of tclsh.  With this solution the tclsh found in the path will find the matching libtclXXX.so.

One could force configure for a location of tclsh.  But then you have to be able to find the matching libtclXXX.so. One could force every execution of tclsh to have the "safe" LD_LIBRARY_PATH but then none of the TCL modulefiles can change LD_LIBRARY_PATH because it has the "wrong" value.

The only safe solution is to configure Lmod  to not use TCL, use only Lua modufiles, and only use the default symlink to mark default versions.  Lmod sets LUA_PATH and LUA_CPATH during the configure step so that it is independent of user changes to those variables.

In order for this patch to be accepted, you'll have to figure out how configure for tclsh location (easy) and somehow let tclsh find its libtclXXX.so WITHOUT using LD_LIBRARY_PATH (hard).

**Comment by rtmclay** [comment]
I have been thinking about this problem and have found a solution.  The trick is to call the tcl programs with:

     LD_LIBRARY_PATH=<found_at_configure> /path/to/tclsh  /path/to/tcl2lua.tcl -L <Current LD_LIBRARY_PATH>

and internally set the LD_LIBRARY_PATH to the current value that was passed in.   Note that I have left the top of the *.tcl programs with #!/usr/bin/env tclsh so that they can be run by hand for testing but Lmod is NOT using that.

If you get a chance, please test 6.4.4 at your site to see if works for you.  Thanks!

**Comment by hartzell** [comment]
I'll give it a try.

In my cases (working with Linuxbrew and Spack (and probably EasyBuild))  the LD_LIBRARY_PATH bit isn't necessary because everything is linked with LDFLAGS that include `-Wl,-rpath=/path/to/lib` but I can see it being a more general solution.

**Thank you** for dedicating the brain cells to it.

**Comment by hartzell** [comment]
6.4.5 works for me in Spack.  I'll file a pull request to undo my little hack there for versions before 6.4.4.

Thanks!

**Pull request closed without merging**
