### PR TITLE
colorize the version numbers in `ml av` with env. var.

### PR DESCRIPTION
**Pull request by simonleary-umass-edu**
https://github.com/tacc/lmod/issues/603

### CODE REVIEW

**Comment by simonleary-umass-edu** [comment]
I think I found the appropriate Lua function to change colors in, but I'm not sure I put the change in the right place. I figured it was best to put it at the beginning of the function that way other color options would override this.

**Comment by simonleary-umass-edu** [comment]
Also not sure if there is potential here for some kind of env. var. injection

**Comment by simonleary-umass-edu** [comment]
Perhaps LMOD_COLORIZE should make this use a default color? I like cyan

**Comment by rtmclay** [comment]
Please look at Lmod 8.7.27 to see how your PR was handled.  There were two issues with your PR. 

1. Some module names do not have to have versions.  Version 8.7.27 fixes that.
2. You had the order of the argument switched when you called colorize() also fixed in 8.7.27.

This functionality needs to be a hook so I created a hook named colorize_fullName() to handle site ability to colorize the sn/version.  To see how I did it please look at contrib/Personal/SitePackage.lua and the only function there: l_colorize_fullName().

The colorize_fullName() hook function had to be moved to MT.lua because of Issue #617. 

You will see that I have three env vars. LMOD_DISPLAY_VERSION_COLOR, LMOD_DISPLAY_SN_COLOR and LMOD_DISPLAY_META_COLOR.  I changed the env names from AVAIL to DISPLAY that  my hook uses because these colors will change the module names for both "module list" and "module avail".  Since these names are in your SitePackage.lua or /etc/lmod/lmod_config.lua, you are free to use any name you like.

I use the last one to colorize modules that have no version.   I like this feature so I'm personally using it.

Note also that the hook takes, fullName and sn.  This way if a site doesn't use the hook they are "paying" for the cost of computing the version when they don't need to.

**Pull request merged**
