### PR TITLE
Contribute French translations

### PR DESCRIPTION
**Pull request by kcgthb**
This commit adds missing French translations for Lmod messages.

### CODE REVIEW

**Comment by rtmclay** [comment]
Thanks for the update on the french translations! I have merged in your PR and pushed to be HEAD.
Do the french have spaces around ':'?  Some of the french messages have spaces around colons and some do not.  I guess "we" should be consistent.

Comments?

**Comment by kcgthb** [comment]
Yes, there should be a space before ':'. I didn't add one for the parts referring to code or commands, but I may have missed some. :+1: for consistency.

**Comment by rtmclay** [comment]
I pushed a new HEAD.  If you don't mind could you look to see the changes about the spaces next to colons are correct?  You should be able to do a diff between HEAD's fr.lua and your version.  Thanks, R.

**Comment by kcgthb** [comment]
Looks great, thanks for fixing the ones I missed!

**Pull request merged**
